In [5]:
import pandas as pd

In [6]:
df_raw = pd.read_excel("../data/raw/Concrete_Data.xls")

In [7]:
df_clean = df_raw.copy()

In [8]:
df_clean.columns = [
    'cement',
    'slag',
    'fly_ash',
    'water',
    'superplasticizer',
    'coarse_aggregate',
    'fine_aggregate',
    'age',
    'strength'
]

In [9]:
df_clean.head()

,cement,slag,fly_ash,water,superplasticizer,coarse_aggregate,fine_aggregate,age,strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075

In [10]:
df_clean.columns

Index(['cement', 'slag', 'fly_ash', 'water', 'superplasticizer',
       'coarse_aggregate', 'fine_aggregate', 'age', 'strength'],
      dtype='str')

In [11]:
df_clean.duplicated().sum()

np.int64(25)

In [12]:
df_clean = df_clean.drop_duplicates().reset_index(drop=True)

In [13]:
df_clean.shape

(1005, 9)

In [14]:
df_clean.duplicated().sum()

np.int64(0)

In [15]:
material_cols = [
    'cement',
    'slag',
    'fly_ash',
    'water',
    'superplasticizer',
    'coarse_aggregate',
    'fine_aggregate'
]

In [16]:
df_clean['mix_id'] = df_clean.groupby(material_cols, sort=False).ngroup()

In [17]:
df_clean.head()

,cement,slag,fly_ash,water,superplasticizer,coarse_aggregate,fine_aggregate,age,strength,mix_id
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111,0
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366,1
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535,2
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780,2
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075,3

In [18]:
df_clean['mix_id'].nunique()

428

In [19]:
def assign_age_stage(age):
    if 1 <= age <= 14:
        return 'Early'
    elif age == 28:
        return '28-day'
    elif 56 <= age <= 365:
        return 'Later'
    else:
        return 'Other'

In [20]:
df_clean['age_stage'] = df_clean['age'].apply(assign_age_stage)

In [21]:
df_clean[['age', 'age_stage']].head(20)

    age age_stage
0    28    28-day
1    28    28-day
2   270     Later
3   365     Later
4   360     Later
5    90     Later
6   365     Later
7    28    28-day
8    28    28-day
9    28    28-day
10   90     Later
11   28    28-day
12  270     Later
13   90     Later
14   28    28-day
15   90     Later
16   90     Later
17  365     Later
18   90     Later
19  180     Later

In [22]:
df_clean['age_stage'].value_counts()

age_stage
28-day    419
Early     315
Later     271
Name: count, dtype: int64

In [23]:
(df_clean['age_stage'] == 'Other').sum()

np.int64(0)

In [24]:
df_clean['mix_id'].nunique()

428

In [25]:
mix_counts = df_clean['mix_id'].value_counts()

(mix_counts > 1).sum()

np.int64(182)

In [26]:
mix_counts[mix_counts > 1].sum()

np.int64(759)

In [27]:
ages_per_mix = df_clean.groupby('mix_id')['age'].nunique()

(ages_per_mix > 1).sum()

np.int64(182)

In [28]:
df_clean.to_csv("../data/processed/concrete_clean.csv", index=False)

In [31]:
df_check = pd.read_csv("../data/processed/concrete_clean.csv")
df_check.shape

(1005, 11)